version: '3.1'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
    restart: always 



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
        - 5672:5672
        - 15672:15672
